global:
  scrape_interval: 2s
scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
        - targets: [ "prometheus:9090" ]
  - job_name: 'springcat'
    static_configs:
      - targets: ['springcat:8080']
    metrics_path: '/actuator/prometheus'
